---
# This role installs and configures virtualization software

# Make sure that the firewall allows ssh for live migration
- name: Start firewall
  service: name=firewalld state=started enabled=yes

- name: Firewall rule for SSH connectivity
  firewalld: service=ssh permanent=true state=enabled immediate=yes
  
- name: Firewall rule for live migration
  firewalld: port=49152-49216/tcp permanent=true state=enabled immediate=yes
  
- name: Setup virtualization bridge
  template: src=roles/virtualization_host/templates/ifcfg-br0.j2 dest=/etc/sysconfig/network-scripts/ifcfg-br0
  
- name: Move interface to bridge
  template: src=roles/virtualization_host/templates/ifcfg-eth0.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ if_name }}
  notify:
  - restart network

- name: Install virtualization software
  yum: name={{ item }} state=present
  with_items:
  - libvirt
  - virt-install
  - qemu-kvm

- name: Start the libvirtd service
  service: name=libvirtd state=started enabled=yes



