---
# This role installs and configures virtualization software

# Make sure that the firewall allows ssh for live migration
- name: Start firewall
  service: name=firewalld state=started enabled=yes

# Distribute SSH keys for live migration
  # Setup SSH Keys
- name: Generate SSH key
  user: name=root generate_ssh_key=yes
  register: rootkeys
  
# Distribute SSH Keys
- name: Distribute SSH keys
  authorized_key:
    key: "{{ hostvars[item].rootkeys.ssh_public_key }}"
    state: present
    user: root
  with_items:
    "{{ groups['cluster_nodes'] }}"
  
- name: Firewall rule for pcsd
  firewalld: service=ssh permanent=true state=enabled immediate=yes

- name: Install virtualization software
  yum: name={{ item }} state=present
  with_items:
  - libvirt
  - virt-install
  - qemu-kvm

- name: Start the libvirtd service
  service: name=libvirtd state=started enabled=yes



